### PR TITLE
Fix listToMaybeS

### LINKED ISSUE #170: listToMaybeS is incorrect
I believe the function `listToMaybeS` is broken. The correct solution could be:

```
exceptToMaybeS :: Monad m => MSF (ExceptT e m) a b -> MSF (MaybeT m) a b
exceptToMaybeS = morphS $ MaybeT . fmap (either (const Nothing) Just) . runExceptT

listToMaybeS :: Monad m => [a] -> MSF (MaybeT m) arbitrary a
listToMaybeS = exceptToMaybeS . runMSFExcept . sequence . map (step . const . return . (, ()))
```

As a low-hanging fruit for beginners who want to contribute, take this correct code and insert it in `Control.Monad.Trans.MSF.Maybe`, and fix the imports.

### PR DESCRIPTION
**Pull request by turion**
Fixes #170

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
Hi! Thanks.

The build broke with:
```
src/Control/Monad/Trans/MSF/Maybe.hs:70:36:
    Could not deduce (Functor m) arising from a use of `fmap'
    from the context (Monad m)
      bound by the type signature for
                 exceptToMaybeS :: Monad m =>
                                   MSF (ExceptT e m) a b -> MSF (MaybeT m) a b
      at src/Control/Monad/Trans/MSF/Maybe.hs:69:19-72
    Possible fix:
      add (Functor m) to the context of
        a type expected by the context: ExceptT e m c -> MaybeT m c
```

Can you add the necessary constraint?

**Comment by turion** [comment]
Done. I always forget that we still build dunai with some GHCs that don't have the Functor-Monad-Hierarchy yet.

**Comment by ivanperez-keera** [comment]
I asked just yesterday about this on fb, twitter and reddit, and there seems to be a number of people who still use 7.*, so I think it's a good idea to keep supporting it.

File: src/Control/Monad/Trans/MSF/Maybe.hs [hunk 1]
```diff
@@ -65,11 +66,14 @@ catchMaybe msf1 msf2 = safely $ do
 
 -- * Converting to and from 'MaybeT'
 
+exceptToMaybeS :: (Functor m, Monad m) => MSF (ExceptT e m) a b -> MSF (MaybeT m) a b
+exceptToMaybeS = morphS $ MaybeT . fmap (either (const Nothing) Just) . runExceptT
```
Comment (ivanperez-keera) [inline src/Control/Monad/Trans/MSF/Maybe.hs]: For info only: what goes in the fmap is:
- http://hackage.haskell.org/package/extra-1.6.18/docs/src/Data.Either.Extra.html#eitherToMaybe
- http://hackage.haskell.org/package/either-4.3.3.2/docs/src/Data-Either-Combinators.html#rightToMaybe
- It also happens to match the behaviour, but not the signature, of https://hackage.haskell.org/package/base-4.12.0.0/docs/src/Data.Maybe.html#listToMaybe. It can also be implemented as `(listToMaybe . toList)`.

It probably makes sense to have something this generic defined somewhere in base, probably in foldable.

I'll happily accept it as is, but it may be useful to know that this expression can be simplified.

File: src/Control/Monad/Trans/MSF/Maybe.hs [hunk 2]
```diff
@@ -65,11 +66,14 @@ catchMaybe msf1 msf2 = safely $ do
...
+
 -- | Converts a list to an 'MSF' in 'MaybeT',
 --   which outputs an element of the list at each step,
 --   throwing 'Nothing' when the list ends.
-listToMaybeS :: Monad m => [b] -> MSF (MaybeT m) a b
-listToMaybeS = foldr iPost exit
+listToMaybeS :: (Functor m, Monad m) => [a] -> MSF (MaybeT m) arbitrary a
+listToMaybeS = exceptToMaybeS . runMSFExcept . sequence . map (step . const . return . (, ()))
```
Comment (ivanperez-keera) [inline src/Control/Monad/Trans/MSF/Maybe.hs]: What is the type of: `exceptToMaybeS . runMSFExcept`?
What is the type of `sequence . map (step . const . return . (, ()))`, and what does it do?

Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: So, when I try to think about this function, it helps me to group this:
```
runMSFExcept . sequence . map (step . const . return . ((\x -> ((), x))))
  :: Monad m => [a1] -> MSF (ExceptT [a1] m) a2 ()
```
What I do not fully understand is why is conceptually correct. This seems to throw an exception with the type of the list at the end.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 1 above)
Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: I think this doesn't match the behaviour of `listToMaybe`. `listToMaybe` forgets the tail of a list.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 2 above)
Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: The exception values are discarded. I'll document that.

> What is the type of `sequence . map (step . const . return . (, ()))`, and what does it do?

It outputs each list element and then throws an exception. I could refactor it as a function in `Control.Monad.Trans.MSF.Except` if you want.

**Comment by turion** [comment]
The build failures suggest that exception handling was unusable on GHC <=7.8 all the time and we didn't notice.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 1 above)
Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: I only mean `either (const Nothing) Just`.

Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: Ah, I see. Yes, I was tempted to use these functions from `extra` or `either`, but didn't want to add a dependency. If you prefer an additional dependency, we can do that as well.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 2 above)
Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: - `sequence . map` is `mapM`.

- Is sequence . map (step . const . return . (, ())) different from `once . const . return`?

Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: > I could refactor it as a function in `Control.Monad.Trans.MSF.Except` if you want.

No need. I'm just trying to understand it and document it. It may help to give names or types to local definitions in a `where` clause.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 1 above)
Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: Nah, it's fine. It may be more appropriate to suggest to the libraries people to give this a name and put it in foldable. The definition is small enough that we can just add it, even if there's a shorter way or is defined in some library (just one small definition does not warrant adding a dependency like that).

There is some relation between foldables, traversables and streams that is bugging me and I can't see clearly, but would make this implementation trivial.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 2 above)
Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: >     * `sequence . map` is `mapM`.

Good point. Fixed. We can even take `mapM_`, to emphasize that the returned list is irrelevant, and only the effect of outputting the elements is important.
 
>     * Is `sequence . map (step . const . return . (, ()))` different from `once . const . return`?

Yes. `once . const . return` does one tick only. But we want to perform one tick for every list element.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 1 above)
Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: I don't see how a function of type `Either e a -> Maybe a` is related to `Foldable` in a meaningful way.

There is definitely a relation between `Foldable`, `Traversable` and `MSF Maybe () a`. A `Foldable` is simply any list structure (without preferring a particular shape like linked lists or balanced trees over others). A `Traversable` is a `Foldable` that is compatible with `Functor`. I think `MSF Maybe () a` is both, because it's basically a list. Compare the signature of `accumulateWith` with `foldr`.

Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: > I don't see how a function of type `Either e a -> Maybe a` is related to `Foldable` in a meaningful way.

There are ways to implement it in which the type would be more general than that. For one example, the implementation in https://hackage.haskell.org/package/base-4.12.0.0/docs/src/Data.Maybe.html#listToMaybe does not mention `Either` at all.

It is too small a piece of code to argue about it. With my original message, I only wanted to point out that this is very specific and there's probably code somewhere that does this for more general types, or that this could be generally useful for other types. If the solution is not immediately obvious, we don't need to act on this and I don't want to open an issue about it. It'll come up again as we clean the code more and more.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 2 above)
Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: I have trouble understanding this. I get it, but I don't get it.

I tried to run it on my machine, and the result I got was the same.

**Comment by ivanperez-keera** [comment]
> The build failures suggest that exception handling was unusable on GHC <=7.8 all the time and we didn't notice.

I am not surprised. I never became familiar enough with the implementation of ExceptT in dunai, and I don't really use it, except for the part that bearriver may be needing, if any.

**Comment by turion** [comment]
> > The build failures suggest that exception handling was unusable on GHC <=7.8 all the time and we didn't notice.
> 
> I am not surprised. I never became familiar enough with the implementation of ExceptT in dunai, and I don't really use it, except for the part that bearriver may be needing, if any.

That's funny. I find exception handling one of the prime achievements of Dunai.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 2 above)
Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: Does it help if I break it up into understandable pieces? This is a big function.

Comment (ivanperez-keera) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: It would, yes. Can you?

It's perfect if the "pieces" are in a where in the same definition. There's no need for now to make them top-level.

**Comment by ivanperez-keera** [comment]
I don't doubt that they are useful. I just could not learn to use them well from the documentation we have right now.

Something that would help me is:
- If the API was grouped based on the types functions operate on (`MSFExcept` vs `MSF ExceptT`).
- If the organization in the file clearly presented a well defined interface (if there is an order in the definitions, it's not immediately obvious to me).
- If the documentation at the top was presented in very simple terms. For example:
```
Generally speaking, MSFs on the Either monad are MSFs that terminate with a
result.

This is an appropriate way of defining MSFs in "steps": first, transformation
one is applied, until it terminates (you are *left* with a result), then we
start applying transformation two until that one terminates (with a result),
and so on. The "results" can be helpful to create the next transformation in
the chain.

It is sometimes convenient to write MSFs in monadic style, such as:
do r1 <- msf1
   r2 <- msf2 r1
   r3 <- msf2 r2
   ... -- and so on

where r1, r2, r3, etc. are the values with which each MSF terminates. To
facilitate using that style, we provide the type MSFExcept, which is
isomorphic to an MSF with an EitherT layer, but with the arguments in the
right order so that they form a monad like the one above. For example:

<show absolutely trivial example here>
```

Points 1 and 2 will happen now. I consider improving the documentation what will come next, but I don't want to spread myself too thin. I want to focus on one thing at a time and forget the documentation for now.

File: src/Control/Monad/Trans/MSF/Maybe.hs (hunk 2 above)
Comment (turion) [reply src/Control/Monad/Trans/MSF/Maybe.hs]: Turns out I could find some good meaning for the pieces. I made them top level now for haddock, if that's ok.
